name = "ai-now-social-publisher"
main = "src/publisher.ts"
compatibility_date = "2024-01-01"

# Cron trigger: Retry failed posts every hour
[triggers]
crons = ["0 * * * *"]

# Observability
[observability]
enabled = true

# R2 Bucket for episode assets (thumbnails, media)
[[r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "ai-now-assets"

# KV for episode metadata and posting status
[[kv_namespaces]]
binding = "EPISODE_METADATA"
id = "8ec5e3e848f24af99888ffca0b703d5e"

[[kv_namespaces]]
binding = "POST_STATUS"
id = "a31d3e98127e4f3989850518ce224c4c"

# Environment variables
[vars]
BASE_URL = "https://www.v2u.us"
DASHBOARD_URL = "https://www.v2u.us/admin/dashboard"